version: "3"

services:
  db:
    image: mariadb:10.6.5
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${DOCKER_PORT_DB}:3306"
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
volumes:
  db_data:
    driver: local